#!/bin/sh
set -e
#echo "checking deps"
#echo "Check for ruby..TBA"

echo updating package list
sudo apt-get update

echo "\nInstalling ruby"
sudo apt-get install ruby-full -y
echo "\nInstalling gcc"
sudo apt-get install gcc -y

echo "installing fluentd"
sudo gem install fluentd

