#!/bin/bash

set -e
trap "rm -f $TMP_1; exit" SIGHUP SIGINT SIGTERM EXIT

TMP_1=__`basename $0`.$$
FORCE=
function usage {
	echo Usage : \./`basename $0` '<name> <tag> [ -f ]';
	exit 1;
}

[ $# -lt 2 ] && { usage; }

NAME=wiziq/$1; shift;
TAG=$1; shift;

while [ $# -gt 0 ];
do
		[ "$1" == "-f" ] && { FORCE='-f'; }
		shift
done;

sudo docker build -f ../specs/chat.docker.spec ../specs | tee $TMP_1
IMAGE_ID=`grep 'Successfully built' $TMP_1 | awk '{ print $3; }'`
echo IMAGE_ID = $IMAGE_ID

sudo docker tag $FORCE $IMAGE_ID $NAME:$TAG
sudo docker images
